services:
  app:
    build: .
    container_name: python_app
  nginx:
    image: s390x/nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cert/cloudflare_origin_cert.pem:/etc/ssl/certs/cloudflare_origin_cert.pem
      - ./cert/cloudflare_origin_key.pem:/etc/ssl/private/cloudflare_origin_key.pem
    depends_on:
      - go_app
  go_app:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017

  mongodb:
    image: s390x/mongo:latest
    ports:
      - "27017:27017"
