services:
  app:
    build: .
    container_name: python_app
    depends_on:
      - redis
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # - ./local_file.txt:/app/local_file.txt
    depends_on:
      - backend
  go_app:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
